### ISSUE TITLE
Lancement de mysql_secure_installation impossible

### ISSUE THREAD

**Issue by LaurentLienhard** [fusionSuite/documentation#1]
en suivant la doc quand j'arrive a la partie execution de `mysql_secure_installation` j'ai une erreur 

```
Enter current password for root (enter for none):
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)
```

pour régler le problème j'ai du faire d'abord 
`/etc/init.d/mariadb start`

et ensuite `mysql_secure_installation` fonctionne

**Comment by snax44** [comment]
Très probablement lie au fonctionnement de ton container.
Sur la plupart des systèmes maria se lance après l'install.
