### ISSUE TITLE
Désactivation du site par défaut

### ISSUE THREAD

**Issue by LaurentLienhard** [fusionSuite/documentation#2]
Dans la doc la commande `rm /etc/nginx/sites-available/default` ne suffit pas, j'ai égalemant du faire `rm /etc/nginx/sites-enabled/default` sinon le service nginx refusé de se relancer

**Comment by snax44** [comment]
C'est normal c'est une erreur de ma part.

c'est:
```
rm /etc/nginx/sites-enabled/default
```
